# Generated by Django 5.0.6 on 2024-07-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapermission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='datapermission',
            name='menu',
            field=models.ManyToManyField(blank=True, help_text='若存在菜单权限，则该权限仅针对所选择的菜单权限生效', null=True, to='system.menu', verbose_name='权限菜单'),
        ),
        migrations.AlterField(
            model_name='datapermission',
            name='mode_type',
            field=models.SmallIntegerField(choices=[(0, '或模式'), (1, '且模式')], default=0, help_text='权限模式, 且模式表示数据需要同时满足规则列表中的每条规则，或模式即满足任意一条规则即可', verbose_name='数据权限模式'),
        ),
        migrations.AlterField(
            model_name='datapermission',
            name='rules',
            field=models.JSONField(max_length=512, verbose_name='规则'),
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='auto_bind',
            field=models.BooleanField(default=False, help_text='注册参数channel的值和该部门code一致，则该用户会自动和该部门绑定', verbose_name='自动绑定'),
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='deptinfo',
            name='mode_type',
            field=models.SmallIntegerField(choices=[(0, '或模式'), (1, '且模式')], default=0, help_text='权限模式, 且模式表示数据需要同时满足规则列表中的每条规则，或模式即满足任意一条规则即可', verbose_name='数据权限模式'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='access',
            field=models.BooleanField(default=False, help_text='允许API接口访问该配置', verbose_name='接口访问'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='inherit',
            field=models.BooleanField(default=False, help_text='允许用户继承该配置', verbose_name='用户继承'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mode_type',
            field=models.SmallIntegerField(choices=[(0, '或模式'), (1, '且模式')], default=0, help_text='权限模式, 且模式表示数据需要同时满足规则列表中的每条规则，或模式即满足任意一条规则即可', verbose_name='数据权限模式'),
        ),
        migrations.AlterField(
            model_name='userpersonalconfig',
            name='access',
            field=models.BooleanField(default=False, help_text='允许API接口访问该配置', verbose_name='接口访问'),
        ),
        migrations.AlterField(
            model_name='userpersonalconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
